USE LifesMomentsDB

GO

CREATE TABLE lmAlbum
(
	albumID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	albumDescription VARCHAR(50) NOT NULL,
	albumDate DATETIME DEFAULT GETDATE() NOT NULL,
	userIDFK INT FOREIGN KEY REFERENCES lmUser(userID) NOT NULL
)