USE LifesMomentsDB

GO

CREATE TABLE lmErrorLog
(
	errorLogID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	sp_Name VARCHAR(100) NOT NULL,
	errorDescription NVARCHAR(MAX) NOT NULL,
	errorDate DATETIME DEFAULT GETDATE() NOT NULL,
	userIDFK INT FOREIGN KEY REFERENCES lmUser(userID) NOT NULL
)